services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: equipment_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - equipment-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin12345
    ports:
      - "8080:80"
    networks:
      - equipment-network
    depends_on:
      - postgres

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=admin12345
      - DB_NAME=equipment_db
    networks:
      - equipment-network
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    networks:
      - equipment-network
    depends_on:
      - server

volumes:
  pgdata:

networks:
  equipment-network:
    driver: bridge
